-- 001_partner_core.up.sql
-- 渠道商主表 + 邀请码 + 客户主表 + customer/partner 切换日志
-- 引用：backend §3.1 / §3.2 / §3.10 / §3.20

CREATE TABLE IF NOT EXISTS `partner` (
    `id`                       BIGINT NOT NULL AUTO_INCREMENT,
    `fy_user_id`               BIGINT NOT NULL COMMENT '关联 fy_api_db.users.id（不建 FK，跨库）',
    `invitation_code`          VARCHAR(64) NOT NULL COMMENT '渠道商专属邀请码（≥16 字符高熵）',
    `status`                   VARCHAR(32) NOT NULL DEFAULT 'applied' COMMENT 'PRD §14.1',
    `kyc_type`                 TINYINT NOT NULL DEFAULT 0 COMMENT '0=未认证 1=企业 2=个人',
    `kyc_status`               TINYINT NOT NULL DEFAULT 0 COMMENT '0..4',
    `kyc_expires_at`           TIMESTAMP(3) NULL COMMENT '年审到期',
    `default_revenue_share`    DECIMAL(6,4) NOT NULL DEFAULT 0.0000,
    `tier`                     TINYINT NOT NULL DEFAULT 0 COMMENT 'markup tier 0-9',
    `applied_at`               TIMESTAMP(3) NOT NULL,
    `approved_at`              TIMESTAMP(3) NULL,
    `approved_by`              BIGINT NULL COMMENT '→ staff.id',
    `contact_name`             VARCHAR(64),
    `contact_phone_cipher`     VARBINARY(512) COMMENT '§19 信封加密',
    `contact_phone_key_id`     VARCHAR(128) COMMENT 'KMS DEK 句柄',
    `contact_email`            VARCHAR(128),
    `contact_email_hmac`       CHAR(64) COMMENT 'v0.2 ARCH M-8.1：HMAC(email) 索引',
    `tax_status`               VARCHAR(32) NOT NULL DEFAULT 'unknown' COMMENT 'v0.2 Compliance HIGH-1',
    `notes`                    TEXT,
    `settlement_provider_id`   BIGINT NULL,
    `provider_sub_account_id`  VARCHAR(128) NOT NULL DEFAULT '',
    `frozen_at`                TIMESTAMP(3) NULL,
    `frozen_reason`            TEXT,
    `terminated_at`            TIMESTAMP(3) NULL,
    `terminated_reason`        TEXT,
    `created_at`               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted_at`               TIMESTAMP(3) NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_partner_fy_user` (`fy_user_id`),
    UNIQUE KEY `uk_partner_invitation_code` (`invitation_code`),
    UNIQUE KEY `uk_partner_email_hmac` (`contact_email_hmac`),
    KEY `idx_partner_status` (`status`, `deleted_at`),
    KEY `idx_partner_kyc` (`kyc_status`, `deleted_at`),
    CONSTRAINT `chk_partner_status` CHECK (`status` IN ('applied','reviewing','approved','rejected','frozen','suspended','terminated')),
    CONSTRAINT `chk_partner_tier` CHECK (`tier` BETWEEN 0 AND 9),
    CONSTRAINT `chk_partner_tax_status` CHECK (`tax_status` IN ('individual','sole_proprietor','individual_business','company','unknown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='渠道商主表 (Phase 1)';

CREATE TABLE IF NOT EXISTS `customer` (
    `id`                       BIGINT NOT NULL AUTO_INCREMENT,
    `fy_user_id`               BIGINT NOT NULL,
    `partner_id`               BIGINT NULL COMMENT 'NULL = 直营客户',
    `joined_via`               VARCHAR(32) NOT NULL DEFAULT 'invitation',
    `invitation_code_used`     VARCHAR(64),
    `status`                   VARCHAR(32) NOT NULL DEFAULT 'active',
    `group_name_in_fy_api`     VARCHAR(128) NOT NULL DEFAULT 'default',
    `quota_limit`              BIGINT NOT NULL DEFAULT 0 COMMENT '0=不限',
    `transferred_from`         BIGINT NULL,
    `transferred_at`           TIMESTAMP(3) NULL,
    `created_at`               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`               TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted_at`               TIMESTAMP(3) NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_customer_fy_user` (`fy_user_id`),
    KEY `idx_customer_partner` (`partner_id`, `deleted_at`),
    KEY `idx_customer_status` (`status`, `partner_id`),
    CONSTRAINT `fk_customer_partner` FOREIGN KEY (`partner_id`) REFERENCES `partner` (`id`),
    CONSTRAINT `chk_customer_status` CHECK (`status` IN ('active','disabled','transferred','orphaned','adopted','direct','deleted')),
    CONSTRAINT `chk_customer_joined` CHECK (`joined_via` IN ('invitation','manual_create','self_register_with_code','direct'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='终端客户主表 (Phase 1)';

CREATE TABLE IF NOT EXISTS `invitation_code` (
    `id`           BIGINT NOT NULL AUTO_INCREMENT,
    `partner_id`   BIGINT NOT NULL,
    `code`         VARCHAR(64) NOT NULL,
    `type`         VARCHAR(16) NOT NULL DEFAULT 'permanent',
    `usage_limit`  INT NOT NULL DEFAULT 0,
    `used_count`   INT NOT NULL DEFAULT 0,
    `expires_at`   TIMESTAMP(3) NULL,
    `status`       VARCHAR(16) NOT NULL DEFAULT 'active',
    `created_at`   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_invitation_code` (`code`),
    KEY `idx_invitation_partner` (`partner_id`, `status`),
    CONSTRAINT `fk_invitation_partner` FOREIGN KEY (`partner_id`) REFERENCES `partner` (`id`),
    CONSTRAINT `chk_invitation_type` CHECK (`type` IN ('permanent','one_time','limited')),
    CONSTRAINT `chk_invitation_status` CHECK (`status` IN ('active','expired','revoked'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='邀请码 (Phase 1)';

CREATE TABLE IF NOT EXISTS `customer_partner_change_log` (
    `id`               BIGINT NOT NULL AUTO_INCREMENT,
    `customer_id`      BIGINT NOT NULL,
    `from_partner_id`  BIGINT NULL,
    `to_partner_id`    BIGINT NULL,
    `initiator_type`   VARCHAR(16) NOT NULL,
    `initiator_id`     BIGINT NOT NULL,
    `status`           VARCHAR(32) NOT NULL DEFAULT 'pending_b' COMMENT 'v0.2 ARCH 8.20',
    `reason`           TEXT,
    `occurred_at`      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `old_group`        VARCHAR(128),
    `new_group`        VARCHAR(128),
    `created_at`       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`       TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    KEY `idx_change_customer` (`customer_id`, `occurred_at`),
    KEY `idx_change_partners` (`from_partner_id`, `to_partner_id`),
    KEY `idx_change_status` (`status`),
    CONSTRAINT `fk_change_customer` FOREIGN KEY (`customer_id`) REFERENCES `customer` (`id`),
    CONSTRAINT `chk_change_initiator` CHECK (`initiator_type` IN ('customer','staff','system_termination')),
    CONSTRAINT `chk_change_status` CHECK (`status` IN ('pending_a','pending_b','pending_staff','completed','rejected','cooldown'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='客户切换渠道商日志 (Phase 1 / 场景 H Phase 2A)';
