-- 005_kyc_invoice_seat.up.sql
-- KYC + 发票 + seat
-- 引用：backend §3.9 / §3.11 / §3.12

CREATE TABLE IF NOT EXISTS `kyc_application` (
    `id`                              BIGINT NOT NULL AUTO_INCREMENT,
    `fy_user_id`                      BIGINT NOT NULL,
    `type`                            TINYINT NOT NULL,
    `status`                          VARCHAR(32) NOT NULL DEFAULT 'draft',
    `business_license_url`            VARCHAR(1024),
    `business_license_ocr_cipher`     VARBINARY(16384) COMMENT 'v0.2 Security MED-13 OCR 加密',
    `business_license_ocr_key_id`     VARCHAR(128),
    `legal_person_name_cipher`        VARBINARY(512),
    `legal_person_name_key_id`        VARCHAR(128),
    `legal_person_name_blind_index`   CHAR(64) COMMENT 'v0.2 Security HIGH-11',
    `legal_person_id_cipher`          VARBINARY(512),
    `legal_person_id_key_id`          VARCHAR(128),
    `legal_person_id_blind_index`     CHAR(64),
    `legal_person_id_url`             VARCHAR(1024),
    `legal_person_id_archive_url`     VARCHAR(1024),
    `alipay_open_id_cipher`           VARBINARY(512),
    `alipay_open_id_key_id`           VARCHAR(128),
    `alipay_real_name_cipher`         VARBINARY(512),
    `alipay_real_name_key_id`         VARCHAR(128),
    `bank_account_cipher`             VARBINARY(512) COMMENT 'Phase 2A',
    `bank_account_key_id`             VARCHAR(128),
    `bank_account_blind_index`        CHAR(64),
    `biometric_liveness_url`          VARCHAR(1024) COMMENT 'v0.2 SEC HIGH-10',
    `biometric_purged_at`             TIMESTAMP(3) NULL,
    `yearly_reject_count`             TINYINT NOT NULL DEFAULT 0 COMMENT 'v0.2 PM MEDIUM-7',
    `yearly_reject_reset_at`          TIMESTAMP(3) NULL,
    `submitted_at`                    TIMESTAMP(3) NULL,
    `reviewed_at`                     TIMESTAMP(3) NULL,
    `reviewed_by`                     BIGINT NULL,
    `reject_reason_code`              VARCHAR(64),
    `reject_reason_text`              TEXT,
    `pii_purged_at`                   TIMESTAMP(3) NULL COMMENT '热归档 30d 后清明文 PII',
    `cold_archive_expires_at`         TIMESTAMP(3) NULL COMMENT 'v0.2 Compliance CRIT-3',
    `created_at`                      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`                      TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted_at`                      TIMESTAMP(3) NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_kyc_fy_user` (`fy_user_id`),
    KEY `idx_kyc_status` (`status`),
    KEY `idx_kyc_purge_hot` (`pii_purged_at`),
    KEY `idx_kyc_purge_cold` (`cold_archive_expires_at`),
    KEY `idx_kyc_biometric_purge` (`biometric_purged_at`),
    KEY `idx_kyc_legal_id_blind` (`legal_person_id_blind_index`),
    KEY `idx_kyc_bank_acct_blind` (`bank_account_blind_index`),
    CONSTRAINT `chk_kyc_type` CHECK (`type` IN (1,2)),
    CONSTRAINT `chk_kyc_status` CHECK (`status` IN ('draft','submitted','under_review','approved','rejected','expiring','expired','frozen_yearly_limit'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='KYC 申请 (Phase 1 stub / 2A 完整)';

CREATE TABLE IF NOT EXISTS `seat` (
    `id`            BIGINT NOT NULL AUTO_INCREMENT,
    `owner_type`    VARCHAR(16) NOT NULL,
    `owner_id`      BIGINT NOT NULL,
    `name`          VARCHAR(128),
    `fy_token_id`   BIGINT NOT NULL,
    `purchased_at`  TIMESTAMP(3) NOT NULL,
    `expires_at`    TIMESTAMP(3) NOT NULL,
    `status`        VARCHAR(16) NOT NULL DEFAULT 'active',
    `created_at`    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    KEY `idx_seat_owner` (`owner_type`, `owner_id`, `status`),
    UNIQUE KEY `uk_seat_token` (`fy_token_id`),
    CONSTRAINT `chk_seat_owner_type` CHECK (`owner_type` IN ('partner','customer')),
    CONSTRAINT `chk_seat_status` CHECK (`status` IN ('active','expired','revoked'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='seat (Phase 3)';

CREATE TABLE IF NOT EXISTS `invoice_title` (
    `id`           BIGINT NOT NULL AUTO_INCREMENT,
    `owner_type`   VARCHAR(16) NOT NULL,
    `owner_id`     BIGINT NOT NULL,
    `title_type`   TINYINT NOT NULL COMMENT '1=个人 2=企业',
    `title`        VARCHAR(255) NOT NULL,
    `tax_number`   VARCHAR(64),
    `bank_info`    TEXT,
    `is_default`   TINYINT(1) NOT NULL DEFAULT 0,
    `created_at`   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`   TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted_at`   TIMESTAMP(3) NULL,
    PRIMARY KEY (`id`),
    KEY `idx_title_owner` (`owner_type`, `owner_id`, `is_default`),
    CONSTRAINT `chk_title_owner_type` CHECK (`owner_type` IN ('partner','customer')),
    CONSTRAINT `chk_title_type` CHECK (`title_type` IN (1,2))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='发票抬头 (Phase 2B)';

CREATE TABLE IF NOT EXISTS `invoice_application` (
    `id`                    BIGINT NOT NULL AUTO_INCREMENT,
    `applicant_type`        VARCHAR(16) NOT NULL,
    `applicant_id`          BIGINT NOT NULL,
    `title_id`              BIGINT NOT NULL,
    `seller_entity_id`      BIGINT NOT NULL COMMENT 'v0.2 Compliance HIGH-6',
    `seller_tax_no`         VARCHAR(64) NOT NULL,
    `amount`                BIGINT NOT NULL,
    `period`                VARCHAR(32),
    `status`                VARCHAR(32) NOT NULL DEFAULT 'applied',
    `invoice_url`           VARCHAR(1024),
    `fapiao_serial`         VARCHAR(64) COMMENT '全电发票流水号',
    `mail_address`          VARCHAR(512),
    `red_flush_request_id`  BIGINT NULL,
    `applied_at`            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `issued_at`             TIMESTAMP(3) NULL,
    `archive_expires_at`    TIMESTAMP(3) NOT NULL COMMENT '≥ 10y 电子会计档案',
    `notes`                 TEXT,
    `reject_reason_code`    VARCHAR(64),
    `reject_reason_text`    TEXT,
    `created_at`            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at`            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    `deleted_at`            TIMESTAMP(3) NULL,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_invoice_fapiao` (`fapiao_serial`),
    KEY `idx_invoice_app_applicant` (`applicant_type`, `applicant_id`, `status`),
    CONSTRAINT `fk_invoice_title` FOREIGN KEY (`title_id`) REFERENCES `invoice_title` (`id`),
    CONSTRAINT `chk_invoice_status` CHECK (`status` IN ('applied','reviewing','issuing','issued','rejected','red_flushing','red_flushed'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='发票申请 (Phase 2B)';

CREATE TABLE IF NOT EXISTS `red_flush_request` (
    `id`                   BIGINT NOT NULL AUTO_INCREMENT,
    `original_invoice_id`  BIGINT NOT NULL,
    `red_fapiao_serial`    VARCHAR(64),
    `reason_code`          VARCHAR(64) NOT NULL,
    `reason_text`          TEXT,
    `status`               VARCHAR(32) NOT NULL DEFAULT 'applied',
    `requested_by`         BIGINT NOT NULL,
    `requested_at`         TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `confirmed_at`         TIMESTAMP(3) NULL,
    `completed_at`         TIMESTAMP(3) NULL,
    `created_at`           TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (`id`),
    KEY `idx_red_flush_original` (`original_invoice_id`),
    CONSTRAINT `fk_red_flush_invoice` FOREIGN KEY (`original_invoice_id`) REFERENCES `invoice_application` (`id`),
    CONSTRAINT `chk_red_flush_status` CHECK (`status` IN ('applied','awaiting_tax_confirm','confirmed','completed','rejected'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='红字发票申请单 (Phase 2B / Compliance MED-17)';
